apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: octant-readonly-everything
rules:
{{- if .Values.clusterRole.rules }}
{{- with .Values.clusterRole.rules }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- else }}
  - apiGroups:
      - ""
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
{{- with .Values.clusterRole.additionalRules }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octant-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "octant.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: octant-readonly-everything
  apiGroup: rbac.authorization.k8s.io
