apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octant.fullname" . }}
  labels:
    {{- include "octant.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "octant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "octant.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "octant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.keycloakGatekeeper.enabled }}
        - name: sso
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: keycloak/keycloak-gatekeeper:latest
          imagePullPolicy: Always
          args:
          - --client-id={{ .Values.keycloakGatekeeper.clientId }}
          - --client-secret={{ .Values.keycloakGatekeeper.clientSecret }}
          - --discovery-url={{ .Values.keycloakGatekeeper.url }}
          - --listen=0.0.0.0:{{ .Values.keycloakGatekeeper.proxyPort }}
          - --upstream-url=http://127.0.0.1:{{ .Values.service.port }}
          - --enable-logging=true
          - --preserve-host=true
          - --enable-refresh-tokens=true
          - --encryption-key={{ include "idp.encryption_key" . }}
          ports:
            - name: http-sso
              containerPort: {{ .Values.keycloakGatekeeper.proxyPort }}
              protocol: TCP
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.fullname }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OCTANT_HTTP_PORT
              value: {{ .Values.service.port | quote }}
          {{- if .Values.extraEnvs }}
            {{- toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: tmp-mount
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp-mount
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
